### ISSUE TITLE
Twitter API integration

### ISSUE THREAD

**Issue by Roman-K93** [kenwheeler/reactive2015#2]
Hello!
I am facing pretty strange issue while I try to integrate Twitter API. I had passed all Fabric integration process successfully, add keys in AppDelegate.m, create the same TwitterAPI class. 
In TwitterAPI.m I got an error **no visible @interface for 'Twitter' declares the selector 'APIClient'** (screenshot attached).
React Native project generated from scratch with no third-party dependencies despite of Fabric.
Have you any suggestions what I am doing wrong and how to solve this issue?
<img width="1392" alt="xcode" src="https://cloud.githubusercontent.com/assets/7987856/16431349/d7ba3d1e-3d88-11e6-8826-598b83c3c35f.png">

Thank you in advance.

**Comment by kenwheeler** [comment]
Are you using fabric to install and link the required libs ?

**Comment by Roman-K93** [comment]
yes, and I didn't have any errors during fabric integration process

**Comment by munkhorgil** [comment]
I know it is too late response and already closed anyway I just figured it out you could try as follows

`TWTRAPIClient *client = [[TWTRAPIClient alloc] init];
NSString *statusesShowEndpoint = @"https://api.twitter.com/1.1/statuses/show.json";
NSURLRequest *request = [client URLRequestWithMethod:@"GET" URL:statusesShowEndpoint parameters:params error:&clientError];
if (request)  [client sendTwitterRequest:request completion:^(NSURLResponse *response, NSData`
